services:
  wyoming-whisper-trt:
    image: captnspdr/wyoming-whisper-trt:latest-igpu
    container_name: wyoming-whisper-trt
    restart: unless-stopped
    environment:
      MODEL:      "${MODEL:-base}"
      LANGUAGE:   "${LANGUAGE:-auto}"
      URI:        "${URI:-tcp://0.0.0.0:10300}"
      DATA_DIR:   "${DATA_DIR:-/data}"
      COMPUTE_TYPE: "${COMPUTE_TYPE:-float16}"
      DEVICE:     "${DEVICE:-cuda}"
      BEAM_SIZE:  "${BEAM_SIZE:-5}"
      STREAMING:  "${STREAMING:-false}"
      DEBUG:      "${DEBUG:-false}"
      NVIDIA_VISIBLE_DEVICES:     all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    network_mode: host
    runtime: nvidia
