---
name: Release
permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches:
      - release/*

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Zip Release
        run: zip -x '*.git*' -r release.zip .

      - name: Extract owner and repo
        uses: jungwinter/split@7f51d99e7cc1f147f6f99be75acf5e641930af88
        id: repo
        with:
          separator: '/'
          msg: ${{ github.repository }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@60d26814e3f06e4ebada05d0d81b1accf09d56b7
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@60d26814e3f06e4ebada05d0d81b1accf09d56b7
        id: gitversion

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@60d26814e3f06e4ebada05d0d81b1accf09d56b7
        with:
          versionSpec: '0.14.x'

      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@60d26814e3f06e4ebada05d0d81b1accf09d56b7
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}
          name: 'Release ${{ steps.gitversion.outputs.majorMinorPatch }}'
          assets: |
            release.zip

      - name: Publish release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/publish@60d26814e3f06e4ebada05d0d81b1accf09d56b7
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          tagName: ${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Close release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/close@60d26814e3f06e4ebada05d0d81b1accf09d56b7
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}
