---
name: Release
on:
  push:
    branches:
      - release/*

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Zip Release
        run: zip -x '*.git*' -r release.zip .

      - name: Extract owner and repo
        uses: winterjung/split@7f51d99e7cc1f147f6f99be75acf5e641930af88
        id: repo
        with:
          separator: '/'
          msg: ${{ github.repository }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        id: gitversion

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          versionSpec: '0.18.x'

      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}
          name: Release ${{ steps.gitversion.outputs.semVer }}
          assets: |
            release.zip

      - name: Publish release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/publish@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Close release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/close@bdf3e6a99aa856b1f341bc37a6eee5e70b46d0c1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}
