---
name: Release
on:
  push:
    branches:
      - release/*

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Zip Release
        run: zip -x '*.git*' -r release.zip .

      - name: Extract owner and repo
        uses: winterjung/split@c9add84449df5452f56c8bc843653cec14eefbf4
        id: repo
        with:
          separator: '/'
          msg: ${{ github.repository }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@a166e44afdb8d18c327b0cb3ae8e454362521c67
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@a166e44afdb8d18c327b0cb3ae8e454362521c67
        id: gitversion

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@a166e44afdb8d18c327b0cb3ae8e454362521c67
        with:
          versionSpec: '0.18.x'

      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@a166e44afdb8d18c327b0cb3ae8e454362521c67
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ steps.gitversion.outputs.MajorMinorPatch }}
          name: ${{ steps.gitversion.outputs.MajorMinorPatch }}
          assets: |
            release.zip

      - name: Publish release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/publish@a166e44afdb8d18c327b0cb3ae8e454362521c67
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ steps.gitversion.outputs.MajorMinorPatch }}

      - name: Close release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/close@a166e44afdb8d18c327b0cb3ae8e454362521c67
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ steps.gitversion.outputs.MajorMinorPatch }}
