---
name: Release
on:
  push:
    branches:
      - release/*

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
        with:
          fetch-depth: 0

      - name: Zip Release
        run: zip -x '*.git*' -r release.zip .

      - name: Extract owner and repo
        uses: winterjung/split@c9add84449df5452f56c8bc843653cec14eefbf4
        id: repo
        with:
          separator: '/'
          msg: ${{ github.repository }}

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@3e0ee0a17f2325d46f3feb4d20dc9a01bd7d617e
        with:
          versionSpec: '0.20.x'

      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@3e0ee0a17f2325d46f3feb4d20dc9a01bd7d617e
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ github.ref_name }}
          name:      ${{ github.ref_name }}
          assets: |
            release.zip

      - name: Publish release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/publish@3e0ee0a17f2325d46f3feb4d20dc9a01bd7d617e
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ github.ref_name }}

      - name: Close release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/close@3e0ee0a17f2325d46f3feb4d20dc9a01bd7d617e
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ github.ref_name }}
